### ISSUE TITLE
mvn install fail

### ISSUE THREAD

**Issue by auppar** [rohanpadhye/vasco#16]
I wish to use vasco to generate precise points to set and calligraphy for android applications.

I am building the application and i see this exception. I see a similar issue earlier for which the soot version was bumped up. Please let me know the probable cause of the exception.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project vasco: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed.: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by rohanpadhye** [comment]
Thanks for noticing this. All of the dependencies have gone out of date and don't support newer versions of Java. Bumping up the versions seems to resolve the issue. Let me know if it persists.
